class oui:
    def __init__(self):
        self.prefix = None
        self.vendor = None


oui_table = [
    {"prefix": "000000", "vendor": "XEROX CORPORATION"},
    {"prefix": "000001", "vendor": "XEROX CORPORATION"},
    {"prefix": "000002", "vendor": "XEROX CORPORATION"},
    {"prefix": "000003", "vendor": "XEROX CORPORATION"},
    {"prefix": "000004", "vendor": "XEROX CORPORATION"},
    {"prefix": "000005", "vendor": "XEROX CORPORATION"},
    {"prefix": "000006", "vendor": "XEROX CORPORATION"},
    {"prefix": "000007", "vendor": "XEROX CORPORATION"},
    {"prefix": "000008", "vendor": "XEROX CORPORATION"},
    {"prefix": "000009", "vendor": "XEROX CORPORATION"},
    {"prefix": "00000A", "vendor": "OMRON TATEISI ELECTRONICS CO."},
    {"prefix": "00000B", "vendor": "MATRIX CORPORATION"},
    {"prefix": "00000C", "vendor": "Cisco Systems, Inc"},
    {"prefix": "00000D", "vendor": "FIBRONICS LTD."},
    {"prefix": "00000E", "vendor": "FUJITSU LIMITED"},
    {"prefix": "00000F", "vendor": "NEXT, INC."},
    {"prefix": "000010", "vendor": "SYTEK INC."},
    {"prefix": "000011", "vendor": "NORMEREL SYSTEMES"},
    {"prefix": "000012", "vendor": "INFORMATION TECHNOLOGY LIMITED"},
    {"prefix": "000013", "vendor": "CAMEX"},
    {"prefix": "000014", "vendor": "NETRONIX"},
    {"prefix": "000015", "vendor": "DATAPOINT CORPORATION"},
    {"prefix": "000016", "vendor": "DU PONT PIXEL SYSTEMS     ."},
    {"prefix": "000017", "vendor": "Oracle Corporation"},
    {"prefix": "000018", "vendor": "WEBSTER COMPUTER CORPORATION"},
    {"prefix": "000019", "vendor": "APPLIED DYNAMICS INTERNATIONAL"},
    {"prefix": "00001A", "vendor": "ADVANCED MICRO DEVICES"},
    {"prefix": "00001B", "vendor": "NOVELL INC."},
    {"prefix": "00001C", "vendor": "BELL TECHNOLOGIES"},
    {"prefix": "00001D", "vendor": "Cabletron Systems, Inc."},
    {"prefix": "00001E", "vendor": "TELSIST INDUSTRIA ELECTRONICA"},
    {"prefix": "00001F", "vendor": "Telco Systems, Inc."},
    {"prefix": "000020", "vendor": "DATAINDUSTRIER DIAB AB"},
    {"prefix": "000021", "vendor": "SUREMAN COMP. & COMMUN. CORP."},
    {"prefix": "000022", "vendor": "VISUAL TECHNOLOGY INC."},
    {"prefix": "000023", "vendor": "ABB INDUSTRIAL SYSTEMS AB"},
    {"prefix": "000024", "vendor": "CONNECT AS"},
    {"prefix": "000025", "vendor": "RAMTEK CORP."},
    {"prefix": "000026", "vendor": "SHA-KEN CO., LTD."},
    {"prefix": "000027", "vendor": "JAPAN RADIO COMPANY"},
    {"prefix": "000028", "vendor": "PRODIGY SYSTEMS CORPORATION"},
    {"prefix": "000029", "vendor": "IMC NETWORKS CORP."},
    {"prefix": "00002A", "vendor": "TRW - SEDD/INP"},
    {"prefix": "00002B", "vendor": "CRISP AUTOMATION, INC"},
    {"prefix": "00002C", "vendor": "AUTOTOTE LIMITED"},
    {"prefix": "00002D", "vendor": "CHROMATICS INC"},
    {"prefix": "00002E", "vendor": "SOCIETE EVIRA"},
    {"prefix": "00002F", "vendor": "TIMEPLEX INC."},
    {"prefix": "000030", "vendor": "VG LABORATORY SYSTEMS LTD"},
    {"prefix": "000031", "vendor": "QPSX COMMUNICATIONS PTY LTD"},
    {"prefix": "000032", "vendor": "Marconi plc"},
    {"prefix": "000033", "vendor": "EGAN MACHINERY COMPANY"},
    {"prefix": "000034", "vendor": "NETWORK RESOURCES CORPORATION"},
    {"prefix": "000035", "vendor": "SPECTRAGRAPHICS CORPORATION"},
    {"prefix": "000036", "vendor": "ATARI CORPORATION"},
    {"prefix": "000037", "vendor": "OXFORD METRICS LIMITED"},
    {"prefix": "000038", "vendor": "CSS LABS"},
    {"prefix": "000039", "vendor": "TOSHIBA CORPORATION"},
    {"prefix": "00003A", "vendor": "CHYRON CORPORATION"},
    {"prefix": "00003B", "vendor": "i Controls, Inc."},
    {"prefix": "00003C", "vendor": "AUSPEX SYSTEMS INC."},
    {"prefix": "00003D", "vendor": "UNISYS"},
    {"prefix": "00003E", "vendor": "SIMPACT"},
    {"prefix": "00003F", "vendor": "SYNTREX, INC."},
    {"prefix": "000040", "vendor": "APPLICON, INC."},
    {"prefix": "000041", "vendor": "ICE CORPORATION"},
    {"prefix": "000042", "vendor": "METIER MANAGEMENT SYSTEMS LTD."},
    {"prefix": "000043", "vendor": "MICRO TECHNOLOGY"},
    {"prefix": "000044", "vendor": "CASTELLE CORPORATION"},
    {"prefix": "000045", "vendor": "FORD AEROSPACE & COMM. CORP."},
    {"prefix": "000046", "vendor": "OLIVETTI NORTH AMERICA"},
    {"prefix": "000047", "vendor": "NICOLET INSTRUMENTS CORP."},
    {"prefix": "000048", "vendor": "SEIKO EPSON CORPORATION"},
    {"prefix": "000049", "vendor": "APRICOT COMPUTERS, LTD"},
    {"prefix": "00004A", "vendor": "ADC CODENOLL TECHNOLOGY CORP."},
    {"prefix": "00004B", "vendor": "ICL DATA OY"},
    {"prefix": "00004C", "vendor": "NEC CORPORATION"},
    {"prefix": "00004D", "vendor": "DCI CORPORATION"},
    {"prefix": "00004E", "vendor": "AMPEX CORPORATION"},
    {"prefix": "00004F", "vendor": "LOGICRAFT, INC."},
    {"prefix": "000050", "vendor": "RADISYS CORPORATION"},
    {"prefix": "000051", "vendor": "HOB ELECTRONIC GMBH & CO. KG"},
    {"prefix": "000052", "vendor": "Intrusion.com, Inc."},
    {"prefix": "000053", "vendor": "COMPUCORP"},
    {"prefix": "000054", "vendor": "Schnieder Electric"},
    {"prefix": "000055", "vendor": "COMMISSARIAT A L`ENERGIE ATOM."},
    {"prefix": "000056", "vendor": "DR. B. STRUCK"},
    {"prefix": "000057", "vendor": "SCITEX CORPORATION LTD."},
    {"prefix": "000058", "vendor": "RACORE COMPUTER PRODUCTS, INC."},
    {"prefix": "000059", "vendor": "HELLIGE GMBH"},
    {"prefix": "00005A", "vendor": "SysKonnect GmbH"},
    {"prefix": "00005B", "vendor": "ELTEC ELEKTRONIK AG"},
    {"prefix": "00005C", "vendor": "TELEMATICS INTERNATIONAL INC."},
    {"prefix": "00005D", "vendor": "CS TELECOM"},
    {"prefix": "00005E", "vendor": "ICANN, IANA Department"},
    {"prefix": "00005F", "vendor": "Sumitomo Electric Industries, Ltd."},
    {"prefix": "000060", "vendor": "KONTRON ELEKTRONIK GMBH"},
    {"prefix": "000061", "vendor": "GATEWAY COMMUNICATIONS"},
    {"prefix": "000062", "vendor": "BULL HN INFORMATION SYSTEMS"},
    {"prefix": "000063", "vendor": "BARCO CONTROL ROOMS GMBH"},
    {"prefix": "000064", "vendor": "Yokogawa Digital Computer Corporation"},
    {"prefix": "000065", "vendor": "Network General Corporation"},
    {"prefix": "000066", "vendor": "TALARIS SYSTEMS, INC."},
    {"prefix": "000067", "vendor": "SOFT * RITE, INC."},
    {"prefix": "000068", "vendor": "ROSEMOUNT CONTROLS"},
    {"prefix": "000069", "vendor": "CONCORD COMMUNICATIONS INC"},
    {"prefix": "00006A", "vendor": "COMPUTER CONSOLES INC."},
    {"prefix": "00006B", "vendor": "SILICON GRAPHICS INC./MIPS"},
    {"prefix": "00006C", "vendor": "PRIVATE"},
    {"prefix": "00006D", "vendor": "CRAY COMMUNICATIONS, LTD."},
    {"prefix": "00006E", "vendor": "ARTISOFT, INC."},
    {"prefix": "00006F", "vendor": "Madge Ltd."},
    {"prefix": "000070", "vendor": "HCL LIMITED"},
    {"prefix": "000071", "vendor": "ADRA SYSTEMS INC."},
    {"prefix": "000072", "vendor": "MINIWARE TECHNOLOGY"},
    {"prefix": "000073", "vendor": "SIECOR CORPORATION"},
    {"prefix": "000074", "vendor": "RICOH COMPANY LTD."},
    {"prefix": "000075", "vendor": "Nortel Networks"},
    {"prefix": "000076", "vendor": "ABEKAS VIDEO SYSTEM"},
    {"prefix": "000077", "vendor": "INTERPHASE CORPORATION"},
    {"prefix": "000078", "vendor": "LABTAM LIMITED"}
]
